In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
# 版本
tf.__version__ # 2.7.0

In [5]:
# 动态图
x = [[1.0]]
m = tf.matmul(x, x) # 这是矩阵乘法
print(m) # 在1.x是无法这样操作的, 必须开启会话

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [7]:
x = tf.constant([[1,9],[3,6]]) # 张量对象
x
# tensor就是张量, 也就是在TF中的基本对象, 可以是进行计算的矩阵.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]])>

### numpy和tf进行转换

In [8]:
x.numpy()

array([[1, 9],
       [3, 6]])

In [10]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 9.],
       [3., 6.]], dtype=float32)>